title = "James Lazo"
baseURL = "https://www.jameslazo.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Phoenix, AZ"
email = "me@jameslazo.com"
favicon = "favicon.ico"
firstName = "James"
lastName = "Lazo"
phone = ""
profileImage = "/img/profile_pic.png"
showEmail = false
showQr = false
showContact = false
showBoards  = false
showCertifications = true
showSocializations = true
sections = ["skills","deployments","contributions","experience","education"]


[params.google]

[params.google.analytics]
trackerID = "XX"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/jameslazo/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/jameslazo/"

[[params.handles]]
    name = "Medium"
    link = "https://medium.com/@james.lazo/"
    icon = "medium"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
